name: tests

on:
  workflow_dispatch:
    inputs:
      site_name:
        description: 'Site Name'
        required: true
        type: choice
        options:
          - nfbusty
          - momlover
          - brattysis
          - nubiles-porn
          - anilos
        default: 'nfbusty'
      email:
        description: EMAIL
        required: false
        default: ""
      password:
        description: PASSWORD
        required: false
        default: "ruby1234"
      acno:
        description: ACNO
        required: false
        default: "903219417861450"
      rtno:
        description: RTNO
        required: false
        default: "063201875"
      use_cache:
        description: "Use Cache (Pip & Browsers)"
        type: boolean
        required: true
        default: true

jobs:
  run-checkout-tests:
    name: test runs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: ${{ github.event.inputs.use_cache == 'true' && 'pip' || '' }}

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Get Playwright Browser Path
        id: playwright-path
        run: echo "path=$(python -c 'import Browser; print(Browser.__path__[0] + \"/wrapper\")')" >> $GITHUB_OUTPUT

      - name: Cache Playwright Browser Binaries
        if: github.event.inputs.use_cache == 'true'
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ${{ steps.playwright-path.outputs.path }}
          key: ${{ runner.os }}-playwright-${{ hashFiles('requirements.txt') }}

      - name: Initialize Playwright Browser Binaries
        if: steps.playwright-cache.outputs.cache-hit != 'true' || github.event.inputs.use_cache != 'true'
        run: |
          python -m Browser.entry init

      - name: Execute TC
        env:
          ACH_DISCORD_WEBHOOK_URL: ${{ secrets.ACH_DISCORD_WEBHOOK_URL }}
        run: |
          python -m robot -d results -t TC01 --variable SITE_NAME:${{ github.event.inputs.site_name || 'nfbusty' }} --variable EMAIL:${{ github.event.inputs.email || '' }} --variable PASSWORD:${{ github.event.inputs.password || 'ruby1234' }} --variable ACNO:${{ github.event.inputs.acno || '903219417861450' }} --variable RTNO:${{ github.event.inputs.rtno || '063201875' }} tests/join.robot

      - name: Upload Test Execution Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-results
          path: results/**