name: robot-tests

on:
  workflow_dispatch:
    inputs:
      email:
        description: EMAIL
        required: false
        default: ""
      acno:
        description: ACNO
        required: false
        default: "903219417861450"
      rtno:
        description: RTNO
        required: false
        default: "063201875"
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Browser (Playwright)
        run: |
          rfbrowser init

      - name: Run TC01
        run: |
          robot -d results -t TC01 --variable EMAIL:${{ github.event.inputs.email || '' }} --variable ACNO:${{ github.event.inputs.acno || '903219417861450' }} --variable RTNO:${{ github.event.inputs.rtno || '063201875' }} tests/join.robot

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-results
          path: results/**